"""
5x7 Bitmap Glyph Map
---------------------

Shared bitmap glyph definitions used by the text rendering pipeline.
These glyphs originated from the legacy text animation system inside
`DesignToolsTab` and are now centralized so they can be reused by the
domain text renderer as well as UI previews.
"""

from __future__ import annotations

from typing import Dict, List

Glyph = List[List[bool]]

# fmt: off
GLYPHS_5X7: Dict[str, Glyph] = {
    ' ': [[False] * 5 for _ in range(7)],
    '!': [
        [True],
        [True],
        [True],
        [True],
        [False],
        [True],
        [False],
    ],
    '"': [
        [True, False, False, False, True],
        [True, False, False, False, True],
        [False, False, False, False, False],
        [False, False, False, False, False],
        [False, False, False, False, False],
        [False, False, False, False, False],
        [False, False, False, False, False],
    ],
    '#': [
        [False, True, False, True, False],
        [True, True, True, True, True],
        [False, True, False, True, False],
        [True, True, True, True, True],
        [False, True, False, True, False],
        [False, False, False, False, False],
        [False, False, False, False, False],
    ],
    '$': [
        [False, True, True, True, False],
        [True, False, True, False, False],
        [False, True, True, True, False],
        [False, False, True, False, True],
        [False, True, True, True, False],
        [False, False, False, False, False],
        [False, False, False, False, False],
    ],
    '%': [
        [True, False, False, False, True],
        [False, False, False, True, False],
        [False, False, True, False, False],
        [False, True, False, False, False],
        [True, False, False, False, True],
        [False, False, False, False, False],
        [False, False, False, False, False],
    ],
    '&': [
        [False, True, True, False, False],
        [True, False, False, True, False],
        [False, True, True, False, False],
        [True, False, False, True, False],
        [False, True, True, False, True],
        [False, False, False, False, False],
        [False, False, False, False, False],
    ],
    "'": [
        [True],
        [True],
        [False],
        [False],
        [False],
        [False],
        [False],
    ],
    '(': [
        [False, False, True],
        [False, True, False],
        [True, False, False],
        [True, False, False],
        [False, True, False],
        [False, False, True],
        [False, False, False],
    ],
    ')': [
        [True, False, False],
        [False, True, False],
        [False, False, True],
        [False, False, True],
        [False, True, False],
        [True, False, False],
        [False, False, False],
    ],
    '*': [
        [False, False, True, False, False],
        [True, False, True, False, True],
        [False, True, True, True, False],
        [True, False, True, False, True],
        [False, False, True, False, False],
        [False, False, False, False, False],
        [False, False, False, False, False],
    ],
    '+': [
        [False, False, False, False, False],
        [False, False, True, False, False],
        [False, False, True, False, False],
        [True, True, True, True, True],
        [False, False, True, False, False],
        [False, False, True, False, False],
        [False, False, False, False, False],
    ],
    ',': [
        [False],
        [False],
        [False],
        [False],
        [False],
        [True],
        [True],
    ],
    '-': [
        [False, False, False, False, False],
        [False, False, False, False, False],
        [False, False, False, False, False],
        [True, True, True, True, True],
        [False, False, False, False, False],
        [False, False, False, False, False],
        [False, False, False, False, False],
    ],
    '.': [
        [False],
        [False],
        [False],
        [False],
        [False],
        [False],
        [True],
    ],
    '/': [
        [False, False, False, False, True],
        [False, False, False, True, False],
        [False, False, True, False, False],
        [False, True, False, False, False],
        [True, False, False, False, False],
        [False, False, False, False, False],
        [False, False, False, False, False],
    ],
    '0': [
        [False, True, True, True, False],
        [True, False, False, False, True],
        [True, False, False, True, True],
        [True, False, True, False, True],
        [True, True, False, False, True],
        [True, False, False, False, True],
        [False, True, True, True, False],
    ],
    '1': [
        [False, False, True, False, False],
        [False, True, True, False, False],
        [False, False, True, False, False],
        [False, False, True, False, False],
        [False, False, True, False, False],
        [False, False, True, False, False],
        [False, True, True, True, False],
    ],
    '2': [
        [False, True, True, True, False],
        [True, False, False, False, True],
        [False, False, False, False, True],
        [False, False, True, True, False],
        [False, True, False, False, False],
        [True, False, False, False, False],
        [True, True, True, True, True],
    ],
    '3': [
        [False, True, True, True, False],
        [True, False, False, False, True],
        [False, False, False, False, True],
        [False, True, True, True, False],
        [False, False, False, False, True],
        [True, False, False, False, True],
        [False, True, True, True, False],
    ],
    '4': [
        [False, False, False, True, False],
        [False, False, True, True, False],
        [False, True, False, True, False],
        [True, False, False, True, False],
        [True, True, True, True, True],
        [False, False, False, True, False],
        [False, False, False, True, False],
    ],
    '5': [
        [True, True, True, True, True],
        [True, False, False, False, False],
        [True, True, True, True, False],
        [False, False, False, False, True],
        [False, False, False, False, True],
        [True, False, False, False, True],
        [False, True, True, True, False],
    ],
    '6': [
        [False, True, True, True, False],
        [True, False, False, False, True],
        [True, False, False, False, False],
        [True, True, True, True, False],
        [True, False, False, False, True],
        [True, False, False, False, True],
        [False, True, True, True, False],
    ],
    '7': [
        [True, True, True, True, True],
        [False, False, False, False, True],
        [False, False, False, True, False],
        [False, False, True, False, False],
        [False, True, False, False, False],
        [True, False, False, False, False],
        [True, False, False, False, False],
    ],
    '8': [
        [False, True, True, True, False],
        [True, False, False, False, True],
        [True, False, False, False, True],
        [False, True, True, True, False],
        [True, False, False, False, True],
        [True, False, False, False, True],
        [False, True, True, True, False],
    ],
    '9': [
        [False, True, True, True, False],
        [True, False, False, False, True],
        [True, False, False, False, True],
        [False, True, True, True, True],
        [False, False, False, False, True],
        [True, False, False, False, True],
        [False, True, True, True, False],
    ],
    ':': [
        [False],
        [False],
        [True],
        [False],
        [True],
        [False],
        [False],
    ],
    ';': [
        [False],
        [False],
        [True],
        [False],
        [True],
        [True],
        [False],
    ],
    '<': [
        [False, False, False, True],
        [False, False, True, False],
        [False, True, False, False],
        [True, False, False, False],
        [False, True, False, False],
        [False, False, True, False],
        [False, False, False, True],
    ],
    '=': [
        [False, False, False, False, False],
        [False, False, False, False, False],
        [True, True, True, True, True],
        [False, False, False, False, False],
        [True, True, True, True, True],
        [False, False, False, False, False],
        [False, False, False, False, False],
    ],
    '>': [
        [True, False, False, False],
        [False, True, False, False],
        [False, False, True, False],
        [False, False, False, True],
        [False, False, True, False],
        [False, True, False, False],
        [True, False, False, False],
    ],
    '?': [
        [False, True, True, True, False],
        [True, False, False, False, True],
        [False, False, False, False, True],
        [False, False, True, True, False],
        [False, False, True, False, False],
        [False, False, False, False, False],
        [False, False, True, False, False],
    ],
    '@': [
        [False, True, True, True, False],
        [True, False, False, False, True],
        [True, False, True, True, True],
        [True, False, True, False, True],
        [True, False, True, True, True],
        [True, False, False, False, False],
        [False, True, True, True, False],
    ],
    'A': [
        [False, True, True, True, False],
        [True, False, False, False, True],
        [True, False, False, False, True],
        [True, True, True, True, True],
        [True, False, False, False, True],
        [True, False, False, False, True],
        [True, False, False, False, True],
    ],
    'B': [
        [True, True, True, True, False],
        [True, False, False, False, True],
        [True, False, False, False, True],
        [True, True, True, True, False],
        [True, False, False, False, True],
        [True, False, False, False, True],
        [True, True, True, True, False],
    ],
    'C': [
        [False, True, True, True, False],
        [True, False, False, False, True],
        [True, False, False, False, False],
        [True, False, False, False, False],
        [True, False, False, False, False],
        [True, False, False, False, True],
        [False, True, True, True, False],
    ],
    'D': [
        [True, True, True, True, False],
        [True, False, False, False, True],
        [True, False, False, False, True],
        [True, False, False, False, True],
        [True, False, False, False, True],
        [True, False, False, False, True],
        [True, True, True, True, False],
    ],
    'E': [
        [True, True, True, True, True],
        [True, False, False, False, False],
        [True, False, False, False, False],
        [True, True, True, True, False],
        [True, False, False, False, False],
        [True, False, False, False, False],
        [True, True, True, True, True],
    ],
    'F': [
        [True, True, True, True, True],
        [True, False, False, False, False],
        [True, False, False, False, False],
        [True, True, True, True, False],
        [True, False, False, False, False],
        [True, False, False, False, False],
        [True, False, False, False, False],
    ],
    'G': [
        [False, True, True, True, False],
        [True, False, False, False, True],
        [True, False, False, False, False],
        [True, False, True, True, True],
        [True, False, False, False, True],
        [True, False, False, False, True],
        [False, True, True, True, False],
    ],
    'H': [
        [True, False, False, False, True],
        [True, False, False, False, True],
        [True, False, False, False, True],
        [True, True, True, True, True],
        [True, False, False, False, True],
        [True, False, False, False, True],
        [True, False, False, False, True],
    ],
    'I': [
        [True, True, True],
        [False, True, False],
        [False, True, False],
        [False, True, False],
        [False, True, False],
        [False, True, False],
        [True, True, True],
    ],
    'J': [
        [False, False, True, True, True],
        [False, False, False, True, False],
        [False, False, False, True, False],
        [False, False, False, True, False],
        [True, False, False, True, False],
        [True, False, False, True, False],
        [False, True, True, False, False],
    ],
    'K': [
        [True, False, False, False, True],
        [True, False, False, True, False],
        [True, False, True, False, False],
        [True, True, False, False, False],
        [True, False, True, False, False],
        [True, False, False, True, False],
        [True, False, False, False, True],
    ],
    'L': [
        [True, False, False, False, False],
        [True, False, False, False, False],
        [True, False, False, False, False],
        [True, False, False, False, False],
        [True, False, False, False, False],
        [True, False, False, False, False],
        [True, True, True, True, True],
    ],
    'M': [
        [True, False, False, False, True],
        [True, True, False, True, True],
        [True, False, True, False, True],
        [True, False, False, False, True],
        [True, False, False, False, True],
        [True, False, False, False, True],
        [True, False, False, False, True],
    ],
    'N': [
        [True, False, False, False, True],
        [True, True, False, False, True],
        [True, False, True, False, True],
        [True, False, False, True, True],
        [True, False, False, False, True],
        [True, False, False, False, True],
        [True, False, False, False, True],
    ],
    'O': [
        [False, True, True, True, False],
        [True, False, False, False, True],
        [True, False, False, False, True],
        [True, False, False, False, True],
        [True, False, False, False, True],
        [True, False, False, False, True],
        [False, True, True, True, False],
    ],
    'P': [
        [True, True, True, True, False],
        [True, False, False, False, True],
        [True, False, False, False, True],
        [True, True, True, True, False],
        [True, False, False, False, False],
        [True, False, False, False, False],
        [True, False, False, False, False],
    ],
    'Q': [
        [False, True, True, True, False],
        [True, False, False, False, True],
        [True, False, False, False, True],
        [True, False, False, False, True],
        [True, False, True, False, True],
        [True, False, False, True, False],
        [False, True, True, False, True],
    ],
    'R': [
        [True, True, True, True, False],
        [True, False, False, False, True],
        [True, False, False, False, True],
        [True, True, True, True, False],
        [True, False, True, False, False],
        [True, False, False, True, False],
        [True, False, False, False, True],
    ],
    'S': [
        [False, True, True, True, False],
        [True, False, False, False, True],
        [True, False, False, False, False],
        [False, True, True, True, False],
        [False, False, False, False, True],
        [True, False, False, False, True],
        [False, True, True, True, False],
    ],
    'T': [
        [True, True, True, True, True],
        [False, False, True, False, False],
        [False, False, True, False, False],
        [False, False, True, False, False],
        [False, False, True, False, False],
        [False, False, True, False, False],
        [False, False, True, False, False],
    ],
    'U': [
        [True, False, False, False, True],
        [True, False, False, False, True],
        [True, False, False, False, True],
        [True, False, False, False, True],
        [True, False, False, False, True],
        [True, False, False, False, True],
        [False, True, True, True, False],
    ],
    'V': [
        [True, False, False, False, True],
        [True, False, False, False, True],
        [True, False, False, False, True],
        [True, False, False, False, True],
        [False, True, False, True, False],
        [False, True, False, True, False],
        [False, False, True, False, False],
    ],
    'W': [
        [True, False, False, False, True],
        [True, False, False, False, True],
        [True, False, False, False, True],
        [True, False, False, False, True],
        [True, False, True, False, True],
        [True, True, False, True, True],
        [True, False, False, False, True],
    ],
    'X': [
        [True, False, False, False, True],
        [False, True, False, True, False],
        [False, False, True, False, False],
        [False, False, True, False, False],
        [False, False, True, False, False],
        [False, True, False, True, False],
        [True, False, False, False, True],
    ],
    'Y': [
        [True, False, False, False, True],
        [False, True, False, True, False],
        [False, False, True, False, False],
        [False, False, True, False, False],
        [False, False, True, False, False],
        [False, False, True, False, False],
        [False, False, True, False, False],
    ],
    'Z': [
        [True, True, True, True, True],
        [False, False, False, False, True],
        [False, False, False, True, False],
        [False, False, True, False, False],
        [False, True, False, False, False],
        [True, False, False, False, False],
        [True, True, True, True, True],
    ],
    '[': [
        [True, True, True],
        [True, False, False],
        [True, False, False],
        [True, False, False],
        [True, False, False],
        [True, False, False],
        [True, True, True],
    ],
    '\\': [
        [True, False, False, False, False],
        [False, True, False, False, False],
        [False, False, True, False, False],
        [False, False, False, True, False],
        [False, False, False, False, True],
        [False, False, False, False, False],
        [False, False, False, False, False],
    ],
    ']': [
        [True, True, True],
        [False, False, True],
        [False, False, True],
        [False, False, True],
        [False, False, True],
        [False, False, True],
        [True, True, True],
    ],
    '^': [
        [False, False, True, False, False],
        [False, True, False, True, False],
        [True, False, False, False, True],
        [False, False, False, False, False],
        [False, False, False, False, False],
        [False, False, False, False, False],
        [False, False, False, False, False],
    ],
    '_': [
        [False, False, False, False, False],
        [False, False, False, False, False],
        [False, False, False, False, False],
        [False, False, False, False, False],
        [False, False, False, False, False],
        [False, False, False, False, False],
        [True, True, True, True, True],
    ],
}
# fmt: on


