/**
 * ESP32 Simple Pattern Player - Upload Bridge Template
 * 
 * Minimal LED pattern player for ESP32
 * Generated by Upload Bridge - github.com/yourname/upload-bridge
 */

#include <FastLED.h>
#include <pgmspace.h>
#include "pattern_data.h"  // Auto-generated by Upload Bridge

// Default settings (overridden by pattern_data.h)
#ifndef DATA_PIN
#define DATA_PIN 2
#endif

#ifndef LED_COUNT
#define LED_COUNT 76
#endif

#define LED_TYPE    WS2812B
#define COLOR_ORDER GRB
#define MAX_LEDS    1024

// LED buffer in RAM
CRGB leds[MAX_LEDS];

void setup() {
    // Initialize FastLED
    FastLED.addLeds<LED_TYPE, DATA_PIN, COLOR_ORDER>(leds, min(LED_COUNT, MAX_LEDS));
    FastLED.setBrightness(BRIGHTNESS);
    FastLED.clear(true);
}

void loop() {
    // Play pattern frames
    for(uint16_t frame = 0; frame < FRAME_COUNT; frame++) {
        // Read frame data from PROGMEM
        for(uint16_t led = 0; led < LED_COUNT; led++) {
            uint32_t pixel_offset = (frame * LED_COUNT + led) * 3;
            
            uint8_t r = pgm_read_byte(pattern_data + pixel_offset);
            uint8_t g = pgm_read_byte(pattern_data + pixel_offset + 1);
            uint8_t b = pgm_read_byte(pattern_data + pixel_offset + 2);
            
            leds[led] = CRGB(r, g, b);
        }
        
        FastLED.show();
        delay(FRAME_DELAY_MS);
    }
}

