from __future__ import annotations

from pathlib import Path
from textwrap import fill
from typing import Dict, List

from core.pattern import Pattern


def _format_pixel_bytes(pixels: List[tuple[int, int, int]], values_per_line: int = 12) -> str:
    byte_strings: List[str] = []
    for r, g, b in pixels:
        byte_strings.append(f"0x{r:02X}")
        byte_strings.append(f"0x{g:02X}")
        byte_strings.append(f"0x{b:02X}")
    chunks = []
    for idx in range(0, len(byte_strings), values_per_line):
        line = ", ".join(byte_strings[idx : idx + values_per_line])
        chunks.append(line)
    return ",\n    ".join(chunks)


def _frame_identifier(index: int) -> str:
    return f"FRAME_{index:03d}"


def available_templates() -> List[str]:
    return list(TEMPLATES.keys())


def render_template(name: str, pattern: Pattern) -> str:
    if name not in TEMPLATES:
        raise KeyError(f"Unknown template '{name}'")
    template = TEMPLATES[name]
    width = pattern.metadata.width
    height = pattern.metadata.height
    fps = pattern.metadata.target_fps or pattern.average_fps
    frame_defs = []
    frame_refs = []
    ref_format = template.get("reference", "{identifier}")
    for idx, frame in enumerate(pattern.frames):
        data = _format_pixel_bytes(frame.pixels)
        frame_defs.append(
            template["frame"].format(
                identifier=_frame_identifier(idx),
                data=data,
                duration=frame.duration_ms,
            )
        )
        frame_refs.append(ref_format.format(identifier=_frame_identifier(idx)))

    return template["body"].format(
        name=pattern.name or "Pattern",
        width=width,
        height=height,
        frame_count=len(pattern.frames),
        fps=fps if fps else 0,
        frame_defs="\n\n".join(frame_defs),
        frame_array=",\n    ".join(frame_refs),
    )


TEMPLATES: Dict[str, Dict[str, str]] = {
    "Arduino PROGMEM": {
        "body": """// Auto-generated by Upload Bridge
#include <avr/pgmspace.h>

const uint8_t MATRIX_WIDTH = {width};
const uint8_t MATRIX_HEIGHT = {height};
const uint16_t FRAME_COUNT = {frame_count};

{frame_defs}

const uint8_t* const FRAMES[] PROGMEM = {{
    {frame_array}
}};
""",
        "frame": """const uint8_t {identifier}[] PROGMEM = {{
    {data}
}};""",
        "reference": "&{identifier}[0]",
    },
    "Plain RGB Hex Array": {
        "body": """// Pattern: {name}
// Dimensions: {width}x{height}, frames: {frame_count}, fps: {fps}

{frame_defs}

const uint8_t* FRAMES[{frame_count}] = {{
    {frame_array}
}};
""",
        "frame": """const uint8_t {identifier}[] = {{
    {data}
}};""",
        "reference": "{identifier}",
    },
    "PIC Assembly Table": {
        "body": """; Pattern: {name}
; Dimensions: {width}x{height}
; Frames: {frame_count}

{frame_defs}

FRAME_POINTERS:
    {frame_array}
""",
        "frame": """{identifier}:
    db {data}
""",
        "reference": "    dw {identifier}",
    },
}

