/**
 * ESP32 LED Pattern Player - Upload Bridge Template
 * 
 * Plays LED animation patterns stored in PROGMEM
 * Generated by Upload Bridge - github.com/yourname/upload-bridge
 */

#include <FastLED.h>
#include <pgmspace.h>
#include "pattern_data.h"  // Auto-generated by Upload Bridge

// Default settings (overridden by pattern_data.h)
#ifndef DATA_PIN
#define DATA_PIN 2
#endif

#ifndef LED_COUNT
#define LED_COUNT 76
#endif

#define LED_TYPE    WS2812B
#define COLOR_ORDER GRB
#define MAX_LEDS    1024

// LED buffer in RAM
CRGB leds[MAX_LEDS];

// Function prototypes
uint16_t read_u16_pgm(const uint8_t *ptr, uint32_t idx);
uint8_t read_u8_pgm(const uint8_t *ptr, uint32_t idx);

void setup() {
    // Initialize serial
    Serial.begin(115200);
    Serial.println();
    Serial.println("ESP32 Pattern Player - Upload Bridge");
    Serial.printf("Data pin: GPIO%d\n", DATA_PIN);
    Serial.printf("Pattern size: %u bytes\n", pattern_data_size);
    
    // Initialize FastLED
    FastLED.addLeds<LED_TYPE, DATA_PIN, COLOR_ORDER>(leds, min(LED_COUNT, MAX_LEDS));
    FastLED.setBrightness(BRIGHTNESS);
    FastLED.clear(true);
    
    // Validate pattern data
    if (pattern_data_size < 4) {
        Serial.println("ERROR: Pattern data invalid!");
        while(1) {
            // Flash red error pattern
            for(int i = 0; i < min(LED_COUNT, MAX_LEDS); i++) {
                leds[i] = CRGB::Red;
            }
            FastLED.show();
            delay(500);
            FastLED.clear(true);
            delay(500);
        }
    }
    
    Serial.printf("LEDs: %d, Frames: %d\n", LED_COUNT, FRAME_COUNT);
    Serial.println("Pattern player ready!");
}

void loop() {
    // Play pattern frames
    for(uint16_t frame = 0; frame < FRAME_COUNT; frame++) {
        // Read frame data from PROGMEM
        for(uint16_t led = 0; led < LED_COUNT; led++) {
            uint32_t pixel_offset = (frame * LED_COUNT + led) * 3;
            
            uint8_t r = read_u8_pgm(pattern_data, pixel_offset);
            uint8_t g = read_u8_pgm(pattern_data, pixel_offset + 1);
            uint8_t b = read_u8_pgm(pattern_data, pixel_offset + 2);
            
            leds[led] = CRGB(r, g, b);
        }
        
        FastLED.show();
        delay(FRAME_DELAY_MS);
    }
}

// Helper functions for PROGMEM access
uint16_t read_u16_pgm(const uint8_t *ptr, uint32_t idx) {
    return pgm_read_word(ptr + idx);
}

uint8_t read_u8_pgm(const uint8_t *ptr, uint32_t idx) {
    return pgm_read_byte(ptr + idx);
}

