/**
 * Pattern Data Header - Auto-generated by Upload Bridge
 * 
 * Contains pattern data and configuration constants
 * Generated for ESP32 platform
 */

#ifndef PATTERN_DATA_H
#define PATTERN_DATA_H

#include <pgmspace.h>

// Pattern configuration
#define LED_COUNT {{led_count}}
#define FRAME_COUNT {{frame_count}}
#define FRAME_DELAY_MS {{frame_delay_ms}}
#define BRIGHTNESS {{brightness}}
#define COLOR_ORDER {{color_order}}

// Pattern data size in bytes
#define pattern_data_size {{pattern_data_size}}

// Pattern data stored in PROGMEM
const uint8_t pattern_data[{{pattern_data_size}}] PROGMEM = {
{{pattern_data_bytes}}
};

#endif // PATTERN_DATA_H

