// pattern_data.h
// Generated by Upload Bridge for ESP8266 WiFi Pattern Player
// This file contains pattern data stored in PROGMEM (flash memory)
// to minimize RAM usage on the ESP8266.

#ifndef PATTERN_DATA_H
#define PATTERN_DATA_H

#include <Arduino.h>

// Pattern metadata
const uint32_t pattern_data_size = 0;  // Size in bytes (0 = no pattern)
const uint8_t pattern_data[] PROGMEM = {
  // Pattern data will be inserted here by Upload Bridge
  // Format: [LED_COUNT_LOW, LED_COUNT_HIGH, FRAME_COUNT_LOW, FRAME_COUNT_HIGH, ...]
  // Each frame: [DELAY_LOW, DELAY_HIGH, R1, G1, B1, R2, G2, B2, ...]
};

#endif // PATTERN_DATA_H