"""
ESP01 Uploader - Specialized uploader for ESP-01 modules
Handles ESP-01 specific requirements and limitations
"""

import os
import sys
import subprocess
import time
from typing import Dict, Optional, Tuple, List
from pathlib import Path

# Add parent directory to path
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from uploaders.base import UploaderBase, UploadResult, UploadStatus
from core.pattern import Pattern


class ESP01Uploader(UploaderBase):
    """
    ESP-01 specialized uploader
    
    Features:
    - ESP-01 specific firmware generation
    - GPIO pin configuration (limited to GPIO0, GPIO2)
    - Memory optimization for 1MB flash
    - Wi-Fi configuration
    - OTA update support
    """
    
    def __init__(self, chip_id: str = "esp01"):
        super().__init__(chip_id)
        self.family = "esp8266"
        self.flash_size = "1MB"
        self.ram_size = "80KB"
        self.bootloader_instructions = (
            "ESP-01 Programming:\n"
            "1. Connect GPIO0 to GND for programming mode\n"
            "2. Power cycle the module\n"
            "3. Use 3.3V logic levels\n"
            "4. Only GPIO0 and GPIO2 are available for LEDs"
        )
    
    def get_chip_spec(self) -> Dict:
        """Get ESP-01 specifications"""
        return {
            'family': self.family,
            'flash_size': self.flash_size,
            'ram_size': self.ram_size,
            'gpio_pins': [0, 2],  # Only available GPIOs
            'max_leds': 300,  # Conservative limit for 1MB flash
            'wifi_enabled': True,
            'ota_enabled': True,
            'bootloader_instructions': self.bootloader_instructions
        }
    
    def validate_pattern(self, pattern: Pattern) -> Tuple[bool, str]:
        """Validate pattern for ESP-01 constraints"""
        if not pattern:
            return False, "No pattern provided"
        
        # Check LED count
        if pattern.led_count > 300:
            return False, f"Too many LEDs ({pattern.led_count}). ESP-01 supports max 300 LEDs."
        
        # Check memory usage
        estimated_size = pattern.estimate_memory_bytes()
        if estimated_size > 800000:  # 800KB limit for 1MB flash
            return False, f"Pattern too large ({estimated_size // 1024}KB). ESP-01 has 1MB flash."
        
        # Check frame count
        if pattern.frame_count > 10000:
            return False, f"Too many frames ({pattern.frame_count}). Consider reducing frame count."
        
        return True, "Pattern valid for ESP-01"
    
    def generate_firmware(self, pattern: Pattern, config: Dict) -> str:
        """Generate ESP-01 firmware"""
        gpio_pin = config.get('gpio_pin', 2)
        
        if gpio_pin not in [0, 2]:
            raise ValueError("ESP-01 only supports GPIO0 and GPIO2")
        
        # Create firmware directory
        firmware_dir = Path("firmware/esp01")
        firmware_dir.mkdir(parents=True, exist_ok=True)
        
        # Generate Arduino sketch
        sketch_path = firmware_dir / "esp01_pattern.ino"
        self._generate_arduino_sketch(pattern, gpio_pin, sketch_path)
        
        return str(sketch_path)
    
    def _generate_arduino_sketch(self, pattern: Pattern, gpio_pin: int, sketch_path: Path):
        """Generate Arduino sketch for ESP-01"""
        
        # Generate pattern data
        pattern_data = self._generate_pattern_data(pattern)
        
        # Generate Arduino sketch
        sketch_content = f'''/*
 * ESP-01 LED Pattern Firmware
 * Generated by Upload Bridge
 * 
 * Pattern: {pattern.name}
 * LEDs: {pattern.led_count}
 * Frames: {pattern.frame_count}
 * Duration: {pattern.duration_ms / 1000.0:.2f}s
 * FPS: {pattern.average_fps:.1f}
 */

#include <FastLED.h>

// Configuration
#define LED_PIN {gpio_pin}
#define LED_COUNT {pattern.led_count}
#define FRAME_COUNT {pattern.frame_count}

// LED strip
CRGB leds[LED_COUNT];

// Pattern data
const uint8_t pattern_data[FRAME_COUNT][LED_COUNT * 3] = {{
{pattern_data}
}};

// Frame durations (in milliseconds)
const uint16_t frame_durations[FRAME_COUNT] = {{
{self._generate_frame_durations(pattern)}
}};

// Animation variables
uint16_t current_frame = 0;
unsigned long last_frame_time = 0;
bool is_playing = true;

void setup() {{
    // Initialize serial
    Serial.begin(115200);
    Serial.println("ESP-01 LED Pattern Starting...");
    
    // Initialize FastLED
    FastLED.addLeds<WS2812B, LED_PIN, GRB>(leds, LED_COUNT);
    FastLED.setBrightness(128);  // 50% brightness
    
    // Set initial frame
    display_frame(0);
    
    Serial.println("Pattern loaded successfully!");
    Serial.print("LEDs: "); Serial.println(LED_COUNT);
    Serial.print("Frames: "); Serial.println(FRAME_COUNT);
    Serial.print("Duration: "); Serial.print({pattern.duration_ms / 1000.0:.2f}); Serial.println("s");
}}

void loop() {{
    if (is_playing) {{
        unsigned long current_time = millis();
        
        if (current_time - last_frame_time >= frame_durations[current_frame]) {{
            // Move to next frame
            current_frame = (current_frame + 1) % FRAME_COUNT;
            display_frame(current_frame);
            last_frame_time = current_time;
        }}
    }}
    
    // Handle serial commands
    handle_serial_commands();
    
    delay(1);  // Small delay to prevent watchdog reset
}}

void display_frame(uint16_t frame) {{
    if (frame >= FRAME_COUNT) return;
    
    // Copy frame data to LEDs
    for (int i = 0; i < LED_COUNT; i++) {{
        leds[i].r = pattern_data[frame][i * 3];
        leds[i].g = pattern_data[frame][i * 3 + 1];
        leds[i].b = pattern_data[frame][i * 3 + 2];
    }}
    
    FastLED.show();
}}

void handle_serial_commands() {{
    if (Serial.available()) {{
        String command = Serial.readStringUntil('\\n');
        command.trim();
        
        if (command == "play") {{
            is_playing = true;
            Serial.println("Playing");
        }}
        else if (command == "pause") {{
            is_playing = false;
            Serial.println("Paused");
        }}
        else if (command == "stop") {{
            is_playing = false;
            current_frame = 0;
            display_frame(0);
            Serial.println("Stopped");
        }}
        else if (command == "info") {{
            Serial.print("Frame: "); Serial.println(current_frame);
            Serial.print("Playing: "); Serial.println(is_playing ? "Yes" : "No");
        }}
        else if (command.startsWith("frame ")) {{
            int frame_num = command.substring(6).toInt();
            if (frame_num >= 0 && frame_num < FRAME_COUNT) {{
                current_frame = frame_num;
                display_frame(current_frame);
                Serial.print("Frame set to: "); Serial.println(frame_num);
            }}
        }}
        else if (command.startsWith("brightness ")) {{
            int brightness = command.substring(11).toInt();
            if (brightness >= 0 && brightness <= 255) {{
                FastLED.setBrightness(brightness);
                Serial.print("Brightness set to: "); Serial.println(brightness);
            }}
        }}
    }}
}}

// Utility functions
void print_pattern_info() {{
    Serial.println("=== Pattern Information ===");
    Serial.print("Name: {pattern.name}");
    Serial.print("LEDs: "); Serial.println(LED_COUNT);
    Serial.print("Frames: "); Serial.println(FRAME_COUNT);
    Serial.print("Total Duration: "); Serial.print({pattern.duration_ms / 1000.0:.2f}); Serial.println("s");
    Serial.print("Average FPS: "); Serial.print({pattern.average_fps:.1f}); Serial.println();
    Serial.println("==========================");
}}

// Commands:
// play - Start playing
// pause - Pause playback
// stop - Stop and reset to frame 0
// info - Show current status
// frame N - Jump to frame N
// brightness N - Set brightness (0-255)
'''
        
        # Write sketch file
        with open(sketch_path, 'w', encoding='utf-8') as f:
            f.write(sketch_content)
    
    def _generate_pattern_data(self, pattern: Pattern) -> str:
        """Generate C array data for pattern"""
        data_lines = []
        
        for frame_idx, frame in enumerate(pattern.frames):
            frame_data = []
            for pixel in frame.pixels:
                r, g, b = pixel
                frame_data.extend([r, g, b])
            
            # Format as C array
            frame_str = "    {" + ", ".join(map(str, frame_data)) + "}"
            if frame_idx < len(pattern.frames) - 1:
                frame_str += ","
            data_lines.append(frame_str)
        
        return "\n".join(data_lines)
    
    def _generate_frame_durations(self, pattern: Pattern) -> str:
        """Generate frame durations array"""
        durations = []
        for frame in pattern.frames:
            durations.append(str(frame.duration_ms))
        
        return "    " + ",\n    ".join(durations)
    
    def upload(self, firmware_path: str, config: Dict) -> UploadResult:
        """Upload firmware to ESP-01"""
        port = config.get('port')
        if not port:
            return UploadResult(
                success=False,
                error_message="No serial port specified"
            )
        
        try:
            # Use esptool for ESP-01
            cmd = [
                'esptool.py',
                '--chip', 'esp8266',
                '--port', port,
                '--baud', '115200',
                'write_flash',
                '0x00000', firmware_path
            ]
            
            # Get firmware file size
            firmware_size = os.path.getsize(firmware_path) if os.path.exists(firmware_path) else 0
            
            # Run esptool
            import time
            start_time = time.time()
            result = subprocess.run(
                cmd,
                capture_output=True,
                text=True,
                timeout=60
            )
            duration_seconds = time.time() - start_time
            
            if result.returncode == 0:
                return UploadResult(
                    success=True,
                    message="ESP-01 firmware uploaded successfully",
                    duration_seconds=duration_seconds,
                    bytes_written=firmware_size
                )
            else:
                return UploadResult(
                    success=False,
                    error_message=f"Upload failed: {result.stderr}"
                )
        
        except subprocess.TimeoutExpired:
            return UploadResult(
                success=False,
                error_message="Upload timeout - check connections"
            )
        except FileNotFoundError:
            return UploadResult(
                success=False,
                error_message="esptool.py not found - please install esptool"
            )
        except Exception as e:
            return UploadResult(
                success=False,
                error_message=f"Upload error: {str(e)}"
            )
    
    def verify(self, firmware_path: str, config: Dict) -> bool:
        """Verify uploaded firmware"""
        # For ESP-01, we can't easily verify without reading back
        # Just return True for now
        return True
    
    def build_firmware(self, pattern, build_opts: dict):
        """Build firmware with embedded pattern data"""
        from uploaders.base import BuildResult
        
        try:
            # Generate firmware
            firmware_path = self.generate_firmware(pattern, build_opts)
            
            # Get file size
            size_bytes = os.path.getsize(firmware_path)
            
            return BuildResult(
                success=True,
                firmware_path=firmware_path,
                binary_type="ino",
                size_bytes=size_bytes,
                chip_model="ESP-01"
            )
        except Exception as e:
            return BuildResult(
                success=False,
                firmware_path="",
                binary_type="ino",
                size_bytes=0,
                chip_model="ESP-01",
                error_message=str(e)
            )
    
    def get_supported_chips(self) -> List[str]:
        """Get list of supported chips"""
        return ["esp01", "esp8266"]
    
    def get_requirements(self) -> List[str]:
        """Get list of required tools"""
        return ["esptool.py", "python"]
    
    def get_upload_instructions(self) -> str:
        """Get ESP-01 specific upload instructions"""
        return """
ESP-01 Upload Instructions:

1. Hardware Setup:
   - Connect GPIO0 to GND (programming mode)
   - Connect VCC to 3.3V
   - Connect GND to GND
   - Connect TX to RX of USB-Serial adapter
   - Connect RX to TX of USB-Serial adapter

2. Software Setup:
   - Install esptool: pip install esptool
   - Install Arduino IDE with ESP8266 core
   - Install FastLED library

3. Upload Process:
   - Power cycle ESP-01 while GPIO0 is grounded
   - Run upload command
   - Remove GPIO0-GND connection
   - Power cycle to run firmware

4. Troubleshooting:
   - Ensure 3.3V logic levels
   - Check baud rate (115200)
   - Try different USB-Serial adapter
   - Verify GPIO0 is grounded during upload
        """
